### ISSUE TITLE
Bot won't respond to get_id...

### ISSUE THREAD

**Issue by magnomad** [alx/BotCast#1]
Hi there,

I've got the bot running, it's logging things I say to backup.csv, and responds to /get_id in a private chat, but not in a group, nor channel, which I created and added the bot to.

Can you offer any suggestions as to how I can debug this?

cheers

Magnus

**Comment by alx** [comment]
Hi Magnus,

Sorry, this is an unmaintained project. From what I can remember, the bot was only used in a private chat, so you'll need to modify it in order to have it interact in a group or a channel.

Thanks for your feedback, hace a nice day,

Alex
